services:
  frontend:
    image: node:22
    ports:
      - "8000:3000"
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env
  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    env_file:
      - .env