import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";

import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Menu } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <div className="flex min-h-screen w-full flex-col">
          <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6 z-10">
            <nav className="hidden flex-col gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
              <span className="flex items-center gap-2 text-lg font-semibold md:text-base">
                &#129367;
                <span className="sr-only">Weird Salads</span>
              </span>
              <Link
                href="/"
                className="text-foreground transition-colors hover:text-foreground"
              >
                POS
              </Link>
              <Link
                href="/stock"
                className="text-muted-foreground transition-colors hover:text-foreground"
              >
                Stock
              </Link>
              <Link
                href="/delivery"
                className="text-muted-foreground transition-colors hover:text-foreground"
              >
                Add delivery
              </Link>
            </nav>
            <Sheet>
              <SheetTrigger asChild>
                <Button
                  variant="outline"
                  size="icon"
                  className="shrink-0 md:hidden"
                >
                  <Menu className="h-5 w-5" />
                  <span className="sr-only">Toggle navigation menu</span>
                </Button>
              </SheetTrigger>
              <SheetContent side="left">
                <nav className="grid gap-6 text-lg font-medium">
                  <Link
                    href="/"
                    className="flex items-center gap-2 text-lg font-semibold"
                  >
                    &#129367;
                    <span className="sr-only">Weird Salads</span>
                  </Link>
                  <Link href="/" className="hover:text-foreground">
                    POS
                  </Link>
                  <Link
                    href="/stock"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Stock
                  </Link>
                  <Link
                    href="/delivery"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Add Delivery
                  </Link>
                </nav>
              </SheetContent>
            </Sheet>
          </header>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
